spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

library:
  name: "My Local Library"
  description: "A simple library management system"
